Feature/database
YanVictorSN/access-control-project pull request #19
Opened 2023-03-28 12:32 UTC by YanVictorSN

Criei o banco de dados em formato JSON e linkei com as páginas correspondentes.

2023-03-28 14:44 UTC, v-amorim commented
Funcionou bem, adicionei entradas e removi, no course_student_list e foi. 
So falta ajustar as sujestões e os conflitos e aprovo

2023-03-28 14:56 UTC, viniam requested changes

2023-03-28 14:56 UTC, viniam commented on src/course_student_list.py
>  UI_PATH = os.path.join(os.path.dirname(CURRENT_FILE_PATH), 'ui', 'course_student_list.ui')
```suggestion
DATABASE_PATH = os.path.join(os.path.dirname(CURRENT_FILE_PATH), 'database', 'student_data.json')
```

2023-03-28 14:56 UTC, viniam commented on src/course_student_list.py
> +        with open('database/student_data.JSON', 'w', encoding="utf-8") as f:
```suggestion
        with open(DATABASE_PATH, 'w', encoding="utf-8") as f:
```

2023-03-28 14:56 UTC, viniam commented on src/course_student_list.py
> +        for i, student in enumerate(self.database["students"]):
```suggestion
        for student in self.database["students"]:
```

2023-03-28 14:56 UTC, viniam commented on src/course_student_list.py
>  UI_PATH = os.path.join(os.path.dirname(CURRENT_FILE_PATH), 'ui', 'course_student_list.ui')
Se puder deixar nesse padrão para todas as chamadas de DATABASE_PATH, assim ele roda de qualquer pasta!

2023-03-28 14:56 UTC, viniam commented on src/course_student_list.py
> +        with open('database/student_data.JSON', 'w', encoding="utf-8") as f:
Se puder deixar nesse padrão para todas as chamadas de DATABASE_PATH, assim ele roda de qualquer pasta!

2023-03-28 14:56 UTC, viniam commented on src/course_student_list.py
> +        for i, student in enumerate(self.database["students"]):
Não precisa desse enumerate aqui, se tiver outros, pode remover

2023-03-28 15:32 UTC, bruno-brn approved these changes

2023-03-28 23:55 UTC, bruno-brn approved these changes

2023-03-29 11:31 UTC, viniam approved these changes

2023-03-29 11:33 UTC, merged